# Jekyll設定
markdown: kramdown
highlighter: rouge

# プラグイン
plugins:
  - jekyll-relative-links
  
# Markdownの処理設定
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
